//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.DBContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        public int Id { get; set; }
        public string ContactPersonName { get; set; }
        public string CompanyName { get; set; }
        public int YearFounded { get; set; }
        public Nullable<int> NumberOfEmployees { get; set; }
        public Nullable<decimal> YearlyRevenue { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyCountry { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyWebsite { get; set; }
        public string AdditionalEMails { get; set; }
        public string CompanyLocation { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
