//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.DBContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyType
    {
        public CompanyType()
        {
            this.CompaniesCompanyType = new HashSet<CompaniesCompanyType>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<CompaniesCompanyType> CompaniesCompanyType { get; set; }
    }
}
