//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.DBContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompaniesCompanyType
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int CompanyTypeId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual CompanyType CompanyType { get; set; }
    }
}
