//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.DBContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class RingImageURL
    {
        public int Id { get; set; }
        public Nullable<int> RingID { get; set; }
        public string RingImageURL1 { get; set; }
    
        public virtual Rings Rings { get; set; }
    }
}
