//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.DBContex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rings
    {
        public Rings()
        {
            this.RingGemstoneType = new HashSet<RingGemstoneType>();
            this.RingImageURL = new HashSet<RingImageURL>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string Decription { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Radius { get; set; }
        public Nullable<decimal> Circumference { get; set; }
        public Nullable<int> GemstoneID { get; set; }
        public Nullable<int> ImageURLID { get; set; }
    
        public virtual GemstoneType GemstoneType { get; set; }
        public virtual ICollection<RingGemstoneType> RingGemstoneType { get; set; }
        public virtual ICollection<RingImageURL> RingImageURL { get; set; }
    }
}
