//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<CompanyType> CompanyType { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Gemstones> Gemstones { get; set; }
        public virtual DbSet<GoldBullionOfferBids> GoldBullionOfferBids { get; set; }
        public virtual DbSet<GoldBullionOffers> GoldBullionOffers { get; set; }
        public virtual DbSet<ImageURL> ImageURL { get; set; }
        public virtual DbSet<JewelryCategories> JewelryCategories { get; set; }
        public virtual DbSet<JewelryItems> JewelryItems { get; set; }
        public virtual DbSet<JewelryItemsImageURL> JewelryItemsImageURL { get; set; }
        public virtual DbSet<JewelryMachines> JewelryMachines { get; set; }
        public virtual DbSet<JewelryMachinesImageURL> JewelryMachinesImageURL { get; set; }
        public virtual DbSet<OrderJewelryItems> OrderJewelryItems { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Promotions> Promotions { get; set; }
    }
}
