//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<CompanyType> CompanyType { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Gemstones> Gemstones { get; set; }
        public virtual DbSet<ImageURL> ImageURL { get; set; }
        public virtual DbSet<JewelryCategories> JewelryCategories { get; set; }
        public virtual DbSet<JewelryItems> JewelryItems { get; set; }
        public virtual DbSet<JewelryMachines> JewelryMachines { get; set; }
        public virtual DbSet<JewelryMachinesImageURL> JewelryMachinesImageURL { get; set; }
        public virtual DbSet<Promotions> Promotions { get; set; }
    }
}
