//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldBullionOfferBids
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int GoldBullionOfferId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual GoldBullionOffers GoldBullionOffers { get; set; }
    }
}
