//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderJewelryItems
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int JewelryItemId { get; set; }
        public int Quantity { get; set; }
        public float Price { get; set; }
    
        public virtual JewelryItems JewelryItems { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
