//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderJewelryItems = new HashSet<OrderJewelryItems>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int CustomerId { get; set; }
        public int SupplierId { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public Nullable<int> DiscountId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Companies Companies1 { get; set; }
        public virtual Discounts Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderJewelryItems> OrderJewelryItems { get; set; }
        public virtual Promotions Promotions { get; set; }
    }
}
