//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotions()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Millem { get; set; }
        public Nullable<decimal> Persent { get; set; }
        public Nullable<decimal> MinOrderGram { get; set; }
        public Nullable<decimal> MinOrderPrice { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public System.DateTime PeriodTo { get; set; }
        public bool Rings { get; set; }
        public bool EngagementRings { get; set; }
        public bool WeddingRings { get; set; }
        public bool NecklacesSets { get; set; }
        public bool NecklacesChains { get; set; }
        public bool ChildrenNecklaceChains { get; set; }
        public bool Sets { get; set; }
        public bool Bracelets { get; set; }
        public bool ChildrenBracelets { get; set; }
        public bool Bangles { get; set; }
        public bool ChildrenBangles { get; set; }
        public bool Earrings { get; set; }
        public bool ChildrenEarrings { get; set; }
        public bool Pendants { get; set; }
        public bool PinBrooch { get; set; }
        public bool Cufflinks { get; set; }
        public bool Watches { get; set; }
        public bool Sunglasses { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
