//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotions()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Millem { get; set; }
        public Nullable<decimal> Persent { get; set; }
        public Nullable<decimal> MinOrderGram { get; set; }
        public Nullable<decimal> MinOrderPrice { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public System.DateTime PeriodTo { get; set; }
        public Nullable<bool> Rings { get; set; }
        public Nullable<bool> EngagementRings { get; set; }
        public Nullable<bool> WeddingRings { get; set; }
        public Nullable<bool> NecklacesSets { get; set; }
        public Nullable<bool> NecklacesChains { get; set; }
        public Nullable<bool> ChildrenNecklaceChains { get; set; }
        public Nullable<bool> Sets { get; set; }
        public Nullable<bool> Bracelets { get; set; }
        public Nullable<bool> ChildrenBracelets { get; set; }
        public Nullable<bool> Bangles { get; set; }
        public Nullable<bool> ChildrenBangles { get; set; }
        public Nullable<bool> Earrings { get; set; }
        public Nullable<bool> ChildrenEarrings { get; set; }
        public Nullable<bool> Pendants { get; set; }
        public Nullable<bool> PinBrooch { get; set; }
        public Nullable<bool> Cufflinks { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
