//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EulerExchangeAppDev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeddingRingsImageURL
    {
        public int Id { get; set; }
        public int WeddingRingId { get; set; }
        public string ImageURL { get; set; }
    
        public virtual WeddingRings WeddingRings { get; set; }
    }
}
